repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: Check .NET formatting
        entry: dotnet format ecosystems.sln --verify-no-changes
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: post-commit-log
        name: Random Programmer Joke on Commit
        entry: bash .githooks/post-commit.sh
        verbose: true
        language: system
        stages: [post-commit]
        always_run: true

      - id: post-merge-deps
        name: Post-Merge Restore Dependencies
        entry: bash -c 'echo -e "\n🔄 Виконано merge! Відновлення NuGet пакетів...\n" && dotnet restore'
        language: system
        stages: [post-merge]
        always_run: true
        verbose: true